### ISSUE TITLE
ADC doesn't work

### ISSUE THREAD

**Issue by bonnee** [eagletrt/eagle-bms#5]
The external ADC of the old design doesn't work. I think it's better to replace it with the new Mainboard's design which seems to work.

**Comment by volpx** [comment]
Old isoADC: LTC1865L
New from fenice: Si8900

**Comment by volpx** [comment]
I'm working on changing the ADC but the Si8900 needs a UART+one output GPIO. So I moved some pins around to use empty pins and now the pinout is full:
![image](https://user-images.githubusercontent.com/48385208/109386976-bcd47a80-78fe-11eb-8deb-888056db7eca.png)

**Comment by volpx** [comment]
If we will need a MCU upgrade this would be a good time to.

**Comment by bonnee** [comment]
Wold going for the same MCU in a bigger package make sense? We don't really need more compute power or peripherals on this board.

**Comment by volpx** [comment]
GG just wrote me suggesting to use the I2C version. Do we have one in the lab to try? On the bus I2C we have two memories at the moment.

**Comment by bonnee** [comment]
We can do with the I2C version. I don't know if we have any of those chips in lab, but I don't think so.
What kind of memories do we have on the bus?

**Comment by volpx** [comment]
two m24m02

**Comment by bonnee** [comment]
Never knew of their existance lol. You can remove one of those.

**Comment by volpx** [comment]
Not a problem if they are there, we can just not populate the footprint. We go for the I2C adc then and call the issue closed once i push.
